name = "kask"
compatibility_date = "2026-02-16"
preview_urls = true

[assets]
directory = "./docs-build"
not_found_handling = "404-page"

[[routes]]
pattern = "kask.ufukty.com"
custom_domain = true

[env.staging]
route = "stage.kask.ufukty.com"

[env.preview]
route = "pr.kask.ufukty.com"
preview_urls = true

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true
