package builder

import (
	"fmt"
	"path/filepath"
	"strings"
	"testing"

	"go.ufukty.com/kask/internal/assert"
	"go.ufukty.com/kask/internal/disk"
	"go.ufukty.com/kask/internal/disk/memory"
)

func TestBuilder_renderWebPages(t *testing.T) {
	expected := "<h1>Title</h1>"
	_, dst := buildTestSite(t, "web", "/")
	assert.ResultInFile(t, expected, dst, "index.html")
}

func TestBuilder_versionStamp(t *testing.T) {
	expected := "<!-- Do not edit. Auto-generated by Kask (devel) -->"
	_, dst := buildTestSite(t, "web", "/")
	assert.ResultInFile(t, expected, dst, "index.html")
}

func TestBuilder_renderMarkdownPages(t *testing.T) {
	_, dst := buildTestSite(t, "markdown-content", "/")
	f, err := dst.ReadFile("index.html")
	if err != nil {
		t.Errorf("prep, read file: %v", err)
	}
	if !strings.Contains(string(f), `<h1 id="title">Title</h1>`) {
		t.Error("expected content not found.")
	}
}

func TestBuilder_renderMarkdownToc(t *testing.T) {
	_, dst := buildTestSite(t, "markdown-toc", "/")
	expected := map[string]string{
		"H1 Lorem":       `<a data-level="1" href="/#h1-lorem">H1 Lorem</a>`,
		"H2 Ipsum":       `<a data-level="2" href="/#h2-ipsum">H2 Ipsum</a>`,
		"H3 Dolor":       `<a data-level="3" href="/#h3-dolor">H3 Dolor</a>`,
		"H4 Sit":         `<a data-level="4" href="/#h4-sit">H4 Sit</a>`,
		"H2 Amet":        `<a data-level="2" href="/#h2-amet">H2 Amet</a>`,
		"H2 Consectetur": `<a data-level="2" href="/#h2-consectetur">H2 Consectetur</a>`,
		"H3 Adipscing":   `<a data-level="3" href="/#h3-adipscing">H3 Adipscing</a>`,
	}
	assert.EachNamedResultInFile(t, expected, dst, "index.html")
}

func TestBuilder_recursiveTemplating(t *testing.T) {
	_, dst := buildTestSite(t, "recursive-templating", "/")
	f, err := dst.ReadFile("a/b/c/page.html")
	if err != nil {
		t.Errorf("prep, read file: %v", err)
	}
	if !strings.Contains(string(f), "./a/b/c/Page") {
		t.Error("expected markdown content not found.")
	}
}

func TestBuilder_propagated(t *testing.T) {
	tcs := []string{"web", "mixed", "markdown"}
	for _, tc := range tcs {
		t.Run(tc, func(t *testing.T) {
			dst := t.TempDir()
			fmt.Println("temp folder:", dst)
			a := Args{
				Src:     disk.NewReal(filepath.Join("testdata/propagated", tc)),
				Dst:     disk.NewReal(dst),
				Dev:     true,
				Verbose: true,
			}
			err := Build(a)
			if err != nil {
				t.Errorf("act, unexpected error: %v", err)
			}
		})
	}
}

func TestBuilder_strippedOrderingHrefs(t *testing.T) {
	b, _ := buildTestSite(t, "stripped-ordering", "/")
	got := hrefs(b.root3)
	expected := []string{
		"/",
		"/career.html",
		"/docs.html",
		"/products.html",
		"/about/",
		"/contact/",
	}
	assert.EachResult(t, expected, got)
}

func TestBuilder_strippedOrderingHrefsWithDomain(t *testing.T) {
	b, _ := buildTestSite(t, "stripped-ordering", "https://kask.ufukty.com/")
	got := hrefs(b.root3)
	expected := map[string]string{
		"/":             "https://kask.ufukty.com/",
		"career.html":   "https://kask.ufukty.com/career.html",
		"docs.html":     "https://kask.ufukty.com/docs.html",
		"products.html": "https://kask.ufukty.com/products.html",
		"about/":        "https://kask.ufukty.com/about/",
		"contact/":      "https://kask.ufukty.com/contact/",
	}
	assert.EachNamedResult(t, expected, got)
}

func TestBuilder_strippedOrderingTitles(t *testing.T) {
	b, _ := buildTestSite(t, "stripped-ordering", "/")
	got := titles(b.root3)
	expected := []string{
		"Website Title",
		"Career Title",
		"Docs Title",
		"Products Title",
		"About Title",
		"Contact Title",
	}
	assert.EachResult(t, expected, got)
}

func TestBuilder_strippedOrderingBreadcrumbs(t *testing.T) {
	b, _ := buildTestSite(t, "stripped-ordering", "/")
	got := breadcrumbs(b.root3)
	expected := []string{
		"Website Title",
		"Website Title / Career Title",
		"Website Title / Docs Title",
		"Website Title / Products Title",
		"Website Title / About Title",
		"Website Title / Contact Title",
	}
	assert.EachResult(t, expected, got)
}

func TestBuilder_preservedOrderingHrefs(t *testing.T) {
	b, _ := buildTestSite(t, "preserved-ordering", "/")
	got := hrefs(b.root3)
	expected := []string{
		"/",
		"/1.career.html",
		"/2.docs.html",
		"/3.products.html",
		"/1.about/",
		"/2.contact/",
	}
	assert.EachResult(t, expected, got)
}

func TestBuilder_preservedOrderingHrefsWithDomain(t *testing.T) {
	b, _ := buildTestSite(t, "preserved-ordering", "https://kask.ufukty.com/")
	got := hrefs(b.root3)
	expected := map[string]string{
		"/":               "https://kask.ufukty.com/",
		"1.career.html":   "https://kask.ufukty.com/1.career.html",
		"2.docs.html":     "https://kask.ufukty.com/2.docs.html",
		"3.products.html": "https://kask.ufukty.com/3.products.html",
		"1.about/":        "https://kask.ufukty.com/1.about/",
		"2.contact/":      "https://kask.ufukty.com/2.contact/",
	}
	assert.EachNamedResult(t, expected, got)
}

func TestBuilder_preservedOrderingTitles(t *testing.T) {
	b, _ := buildTestSite(t, "preserved-ordering", "/")
	got := titles(b.root3)
	expected := []string{
		"Website Title",
		"Career Title",
		"Docs Title",
		"Products Title",
		"About Title",
		"Contact Title",
	}
	assert.EachResult(t, expected, got)
}

func TestBuilder_preservedOrderingBreadcrumbs(t *testing.T) {
	b, _ := buildTestSite(t, "preserved-ordering", "/")
	got := breadcrumbs(b.root3)
	expected := []string{
		"Website Title",
		"Website Title / Career Title",
		"Website Title / Docs Title",
		"Website Title / Products Title",
		"Website Title / About Title",
		"Website Title / Contact Title",
	}
	assert.EachResult(t, expected, got)
}

func TestBuilder_cssSplitting(t *testing.T) {
	_, dst := buildTestSite(t, "css-splitting", "https://kask.ufukty.com/")

	t.Run("links", func(t *testing.T) {
		expected := map[string]string{
			"styles.propagate.css":   `"https://kask.ufukty.com/styles.propagate.css"`,
			"a/styles.propagate.css": `"https://kask.ufukty.com/a/styles.propagate.css"`,
			"a/styles.css":           `"https://kask.ufukty.com/a/styles.css"`,
		}
		unexpected := map[string]string{
			"styles.css": `"https://kask.ufukty.com/styles.css"`,
		}
		assert.NamedResultsInFile(t, expected, unexpected, dst, "a/index.html")
	})

	t.Run("contents", func(t *testing.T) {
		assert.ResultsInFiles(t, dst, map[string]string{
			"/styles.css":             ":root {}",
			"/styles.propagate.css":   ":root.propagated {}",
			"/a/styles.css":           ".a {}",
			"/a/styles.propagate.css": ".a.propagated {}",
		})
	})
}

func TestBuilder_titles(t *testing.T) {
	b, _ := buildTestSite(t, "titles", "/")
	got := titles(b.root3)
	expected := []string{
		".",
		"An Anonymous Markdown Page",
		"An Anonymous Web Page",
		"A beatiful markdown file with title",
		"A beautiful tmpl file with title tag",
	}
	assert.EachResult(t, expected, got)
}

func TestBuilder_metaTitle(t *testing.T) {
	b, _ := buildTestSite(t, "meta-title", "/")
	got := titles(b.root3)
	expected := []string{
		"My Beautiful Site",
		"Page1",
		"My Beautiful Section",
		"Page2",
	}
	assert.EachResult(t, expected, got)
}

func TestBuilder_assets(t *testing.T) {
	_, dst := buildTestSite(t, "assets", "/")
	tcs := []string{".assets/sample.txt", "section/.assets/subsample.txt"}
	for _, tc := range tcs {
		assertfile(t, dst, tc)
	}
}

func TestBuilder_assetLinking(t *testing.T) {
	_, dst := buildTestSite(t, "asset-linking", "https://kask.ufukty.com/")

	t.Run("Markdown based page", func(t *testing.T) {
		expected := `<p><img src="https://kask.ufukty.com/.assets/img%402.jpg" alt="" /></p>`
		assert.ResultInFile(t, expected, dst, "markdown.html")
	})

	t.Run("Html based page", func(t *testing.T) {
		expected := `<img src="https://kask.ufukty.com/.assets/img%402.jpg">`
		assert.ResultInFile(t, expected, dst, "template.html")
	})
}

func TestBuilder_workersConfigurationFile(t *testing.T) {
	dst := memory.New()
	args := Args{
		Src:      disk.NewReal("testdata/workers"),
		Dst:      dst,
		Provider: ProviderCloudflareWorkers,
	}
	err := Build(args)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}
	expected := map[string]string{
		"Top level asset dir": lines(
			"/.assets/*",
			"  Cache-Control: public, max-age=14400, must-revalidate",
		),
		"Second level asset dir": lines(
			"/section/.assets/*",
			"  Cache-Control: public, max-age=14400, must-revalidate",
		),
	}
	assert.EachNamedResultInFile(t, expected, dst, "_headers")
}

func TestBuilder_tmplLinkReplacements(t *testing.T) {
	_, dst := buildTestSite(t, "link-replacements", "/")

	t.Run("Markdown based pages", func(t *testing.T) {
		expected := []string{
			`<a href="/a/b/#Title">subdir direct</a>`,
			`<a href="/a/b/#Title">subdir absolute</a>`,
			`<a href="/a/b/#Title">subdir redundancies</a>`,
			`<a href="/a/tmpl.html#Title">sibling</a>`,
		}
		got, err := findAnchorTags(dst, "a/md.html")
		if err != nil {
			t.Errorf("find anchor tags: %v", err)
		}
		assert.EachResult(t, expected, got)
	})

	t.Run("Html based page", func(t *testing.T) {
		expected := []string{
			`<a href="/a/b/#Title">subdir direct</a>`,
			`<a href="/a/b/#Title">subdir absolute</a>`,
			`<a href="/a/b/#Title">subdir redundancies</a>`,
			`<a href="/a/md.html#Title">sibling</a>`,
		}
		got, err := findAnchorTags(dst, "a/tmpl.html")
		if err != nil {
			t.Errorf("find anchor tags: %v", err)
		}
		assert.EachResult(t, expected, got)
	})
}

func TestBuilder_linkCanonicalization(t *testing.T) {
	_, dst := buildTestSite(t, "canonicalization", "/")

	t.Run("Markdown based page", func(t *testing.T) {
		expected := map[string]string{
			"absolute":           `<a href="/targets/absolute.html"></a>`,
			"relative":           `<a href="/targets/relative.html"></a>`,
			"relative-redundant": `<a href="/targets/relative-redundant.html"></a>`,
		}
		got, err := findAnchorTags(dst, "page1.html")
		if err != nil {
			t.Errorf("find anchor tags: %v", err)
		}
		assert.EachNamedResult(t, expected, got)
	})

	t.Run("Html based page", func(t *testing.T) {
		expected := map[string]string{
			"absolute":           `<a href="/targets/absolute.html"></a>`,
			"relative":           `<a href="/targets/relative.html"></a>`,
			"relative-redundant": `<a href="/targets/relative-redundant.html"></a>`,
		}
		got, err := findAnchorTags(dst, "page2.html")
		if err != nil {
			t.Errorf("find anchor tags: %v", err)
		}
		assert.EachNamedResult(t, expected, got)
	})
}

func TestBuilder_docs(t *testing.T) {
	err := Build(Args{
		Src:      disk.NewReal("../../docs"), // TODO: use on-memory FS
		Dst:      disk.NewReal(t.TempDir()),  // TODO: use on-memory FS
		Domain:   "https://kask.ufukty.com/",
		Dev:      false,
		Verbose:  false,
		Provider: "",
	})
	if err != nil {
		t.Errorf("act, unexpected error: %v", err)
	}
}

func TestBuilder_hiddenPagesDst(t *testing.T) {
	_, dst := buildTestSite(t, "hidden-pages", "/")
	got, err := files(dst)
	if err != nil {
		t.Errorf("list files: %v", err)
	}
	expected := []string{
		"404.html",
		"career.html",
		"index.html",
		"products.html",
		"sitemap.html",
	}
	assert.EachResult(t, expected, got)
}

func TestBuilder_hiddenPagesSitemap(t *testing.T) {
	b, _ := buildTestSite(t, "hidden-pages", "/")
	got := titles(b.root3)
	expected := []string{
		"Index",
		"Career",
		"Products",
	}
	assert.EachResult(t, expected, got)
}
