package builder

import (
	"fmt"
	"html/template"
	"path/filepath"
	"strings"
	"time"

	"go.ufukty.com/kask/cmd/kask/commands/version"
	"go.ufukty.com/kask/internal/builder/directory"
	"go.ufukty.com/kask/internal/builder/markdown"
	"go.ufukty.com/kask/internal/builder/paths"
	"go.ufukty.com/kask/internal/builder/rewriter"
	"go.ufukty.com/kask/pkg/kask"
)

var fileheader = fmt.Sprintf("<!-- Do not edit. Auto-generated by Kask %s -->", version.Version)

type Provider string

const (
	ProviderDefault           Provider = ""
	ProviderCloudflareWorkers Provider = "cfw"
)

func (p Provider) UrlMode() paths.UrlMode {
	if p == ProviderCloudflareWorkers {
		return paths.UrlModeExtless
	}
	return paths.UrlModeDefault
}

type Args struct {
	Src, Dst string
	Domain   string
	Dev      bool // suffixes css bundles with unique ids to bypass browser caching
	Verbose  bool
	Provider Provider
}

type builder struct {
	args     Args
	rw       *rewriter.Rewriter
	assets   []string                  // src
	markdown map[string]*kask.Markdown // src -> content
	leaves   map[string]*kask.Node     // dst -> node
	root3    *kask.Node                // for testing
	start    time.Time
}

func has[K comparable, V any](m map[K]V, k K) bool {
	_, ok := m[k]
	return ok
}

func (b *builder) checkCompetingEntries(dir *directory.Dir) error {
	children := map[string]int{}
	for _, subdir := range dir.Subdirs {
		children[subdir.Name] = 1
	}
	for _, page := range dir.Pages {
		if has(children, page) {
			children[page] = -1
		}
		children[page]++
	}
	duplicates := []string{}
	for child, freq := range children {
		if freq > 1 {
			duplicates = append(duplicates, child)
		}
	}
	if len(duplicates) > 0 {
		return fmt.Errorf("multiple entries sharing the same path for those: %s", strings.Join(duplicates, ", "))
	}
	for _, sub := range dir.Subdirs {
		if err := b.checkCompetingEntries(sub); err != nil {
			return fmt.Errorf("%q: %w", sub.Name, err)
		}
	}
	return nil
}

// used in assigning destination addresses, bundling css, and propagating tmpl files
type dir2 struct {
	original    *directory.Dir
	paths       paths.Paths
	subdirs     []*dir2
	stylesheets []string // dst paths
	templates   *template.Template
}

func (b *builder) toDir2(d, p *directory.Dir, parent paths.Paths) *dir2 {
	paths := parent.Subdir(d.Name, p.IsToStrip())
	d2 := &dir2{
		original:    d,
		subdirs:     []*dir2{},
		paths:       paths,
		stylesheets: nil,
		templates:   nil,
	}
	for _, subdir := range d.Subdirs {
		d2.subdirs = append(d2.subdirs, b.toDir2(subdir, d, paths))
	}
	return d2
}

// TODO: domain prefix
func (b *builder) toNode(d *dir2, parent *kask.Node) (*kask.Node, error) {
	n := &kask.Node{
		Title:    "",
		Href:     "",
		Parent:   parent,
		Children: []*kask.Node{},
	}

	for _, page := range d.original.Pages {
		p := d.paths.File(page, d.original.IsToStrip(), b.args.Provider.UrlMode()) // TODO: reuse calculated paths for later use in [builder.Build]
		title, err := pageTitle(b.args.Src, p)
		if err != nil {
			return nil, fmt.Errorf("decide on title: %w", err)
		}
		if page == "README.md" || page == "index.tmpl" {
			n.Href = p.Url
			n.Title = title
			b.rw.Bank(p.Src, p.Url)
			b.rw.Bank(filepath.Dir(p.Src), p.Url)
		} else {
			c := &kask.Node{
				Title:    title,
				Href:     p.Url,
				Parent:   n,
				Children: []*kask.Node{},
			}
			b.rw.Bank(p.Src, p.Url)
			b.leaves[p.Url] = c
			n.Children = append(n.Children, c)
		}
	}

	if n.Title == "" {
		if d.original.Meta != nil {
			n.Title = d.original.Meta.Title
		} else {
			n.Title = filepath.Base(d.paths.Dst)
		}
	}

	b.leaves[d.paths.Url] = n

	for _, subdir := range d.subdirs {
		s, err := b.toNode(subdir, n)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", filepath.Base(d.paths.Src), err)
		}
		n.Children = append(n.Children, s)
	}

	return n, nil
}

func (b *builder) renderMarkdown(d *dir2) error {
	for _, page := range d.original.Pages {
		if filepath.Ext(page) == ".md" {
			p := d.paths.File(page, d.original.IsToStrip(), b.args.Provider.UrlMode())
			html, err := markdown.ToHtml(b.args.Src, p, b.rw)
			if err != nil {
				return fmt.Errorf("rendering %s: %w", page, err)
			}
			b.markdown[p.Src] = html
		}
	}
	for _, subdir := range d.subdirs {
		if err := b.renderMarkdown(subdir); err != nil {
			return fmt.Errorf("%q: %w", filepath.Base(subdir.paths.Src), err)
		}
	}
	return nil
}

// [builder.Build] run separate DFS processes because there are many steps
// involving previous's complete results like templates can access to the
// sitemap which contains headers extracted from markdown files
func (b *builder) Build() error {
	root, err := directory.Inspect(b.args.Src)
	if err != nil {
		return fmt.Errorf("inspecting source directory: %w", err)
	}
	if err := b.checkCompetingEntries(root); err != nil {
		return fmt.Errorf("checking competing files and folders: %w", err)
	}
	root2 := b.toDir2(root, nil, paths.Paths{Src: "."})
	if err := b.bundleAndPropagateStylesheets(root2, []string{}); err != nil {
		return fmt.Errorf("bundling stylesheets: %w", err)
	}
	if err := b.propagateTemplates(root2, newTemplateSet()); err != nil {
		return fmt.Errorf("bundling stylesheets: %w", err)
	}
	b.root3, err = b.toNode(root2, nil)
	if err != nil {
		return fmt.Errorf("structuring node tree: %w", err)
	}
	if err := b.renderMarkdown(root2); err != nil {
		return fmt.Errorf("rendering markdown pages: %w", err)
	}
	if err := b.execDir(root2); err != nil {
		return fmt.Errorf("executing templates: %w", err)
	}
	if err := b.copyAssetsFolders(root2); err != nil {
		return fmt.Errorf("copying assets folders: %w", err)
	}
	if err := b.createDeploymentConfiguration(root2); err != nil {
		return fmt.Errorf("copying assets folders: %w", err)
	}
	return nil
}

// split for testing
func newBuilder(args Args) *builder {
	return &builder{
		args:     args,
		rw:       rewriter.New(),
		assets:   []string{},
		markdown: map[string]*kask.Markdown{},
		leaves:   map[string]*kask.Node{},
		start:    time.Now(),
	}
}

func Build(args Args) error {
	return newBuilder(args).Build()
}
