package builder

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"go.ufukty.com/kask/internal/disk"
	"go.ufukty.com/kask/pkg/kask"
)

func TestBuilder_renderWebPages(t *testing.T) {
	_, tmp := buildTestSite("testdata/web", "/")
	f, err := os.ReadFile(filepath.Join(tmp, "index.html"))
	if err != nil {
		t.Errorf("prep, read file: %v", err)
	}
	if !strings.Contains(string(f), "<h1>Title</h1>") {
		t.Error("expected markdown content not found.")
	}
}

func TestBuilder_renderMarkdownPages(t *testing.T) {
	_, tmp := buildTestSite("testdata/markdown-content", "/")
	f, err := os.ReadFile(filepath.Join(tmp, "index.html"))
	if err != nil {
		t.Errorf("prep, read file: %v", err)
	}
	if !strings.Contains(string(f), `<h1 id="title">Title</h1>`) {
		t.Error("expected content not found.")
	}
}

func ExampleBuilder_renderMarkdownToc() {
	_, tmp := buildTestSite("testdata/markdown-toc", "/")
	f, err := os.ReadFile(filepath.Join(tmp, "index.html"))
	if err != nil {
		panic(fmt.Errorf("prep, read file: %w", err))
	}
	fmt.Println(string(f))
	// Output:
	// <!-- Do not edit. Auto-generated by Kask (devel) -->
	// <a data-level="1" href="/#h1-lorem">H1 Lorem</a>
	// <a data-level="2" href="/#h2-ipsum">H2 Ipsum</a>
	// <a data-level="3" href="/#h3-dolor">H3 Dolor</a>
	// <a data-level="4" href="/#h4-sit">H4 Sit</a>
	// <a data-level="2" href="/#h2-amet">H2 Amet</a>
	// <a data-level="2" href="/#h2-consectetur">H2 Consectetur</a>
	// <a data-level="3" href="/#h3-adipscing">H3 Adipscing</a>
}

func TestBuilder_recursiveTemplating(t *testing.T) {
	_, tmp := buildTestSite("testdata/recursive-templating", "/")
	f, err := os.ReadFile(filepath.Join(tmp, "a/b/c/page.html"))
	if err != nil {
		t.Errorf("prep, read file: %v", err)
	}
	if !strings.Contains(string(f), "./a/b/c/Page") {
		t.Error("expected markdown content not found.")
	}
}

func TestBuilder_propagated(t *testing.T) {
	tcs := []string{"web", "mixed", "markdown"}
	for _, tc := range tcs {
		t.Run(tc, func(t *testing.T) {
			tmp, err := os.MkdirTemp(os.TempDir(), "kask-test-build-*")
			if err != nil {
				t.Errorf("os.MkdirTemp: %v", err)
			}
			fmt.Println("temp folder:", tmp)

			a := Args{
				Src:     filepath.Join("testdata/propagated", tc),
				Dst:     tmp,
				Dev:     true,
				Verbose: true,
			}
			err = Build(a)
			if err != nil {
				t.Errorf("act, unexpected error: %v", err)
			}
		})
	}
}

func ExampleBuilder_strippedOrderingHrefs() {
	b, _ := buildTestSite("testdata/stripped-ordering", "/")
	dfs([]*kask.Node{b.root3}, func(n []*kask.Node) { fmt.Println(n[len(n)-1].Href) })
	// Output:
	// /
	// /career.html
	// /docs.html
	// /products.html
	// /about/
	// /contact/
}

func ExampleBuilder_strippedOrderingHrefsWithDomain() {
	b, _ := buildTestSite("testdata/stripped-ordering", "https://kask.ufukty.com/")
	dfs([]*kask.Node{b.root3}, func(n []*kask.Node) { fmt.Println(n[len(n)-1].Href) })
	// Output:
	// https://kask.ufukty.com/
	// https://kask.ufukty.com/career.html
	// https://kask.ufukty.com/docs.html
	// https://kask.ufukty.com/products.html
	// https://kask.ufukty.com/about/
	// https://kask.ufukty.com/contact/
}

func ExampleBuilder_strippedOrderingTitles() {
	b, _ := buildTestSite("testdata/stripped-ordering", "/")
	dfs([]*kask.Node{b.root3}, func(n []*kask.Node) { fmt.Println(n[len(n)-1].Title) })
	// Output:
	// Website Title
	// Career Title
	// Docs Title
	// Products Title
	// About Title
	// Contact Title
}

func ExampleBuilder_strippedOrderingBreadcrumbs() {
	b, _ := buildTestSite("testdata/stripped-ordering", "/")
	dfs([]*kask.Node{b.root3}, func(n []*kask.Node) {
		bs := each(n, func(n *kask.Node) string { return n.Title })
		fmt.Println(strings.Join(bs, " / "))
	})
	// Output:
	// Website Title
	// Website Title / Career Title
	// Website Title / Docs Title
	// Website Title / Products Title
	// Website Title / About Title
	// Website Title / Contact Title
}

func ExampleBuilder_preservedOrderingHrefs() {
	b, _ := buildTestSite("testdata/preserved-ordering", "/")
	dfs([]*kask.Node{b.root3}, func(n []*kask.Node) { fmt.Println(n[len(n)-1].Href) })
	// Output:
	// /
	// /1.career.html
	// /2.docs.html
	// /3.products.html
	// /1.about/
	// /2.contact/
}

func ExampleBuilder_preservedOrderingHrefsWithDomain() {
	b, _ := buildTestSite("testdata/preserved-ordering", "https://kask.ufukty.com/")
	dfs([]*kask.Node{b.root3}, func(n []*kask.Node) { fmt.Println(n[len(n)-1].Href) })
	// Output:
	// https://kask.ufukty.com/
	// https://kask.ufukty.com/1.career.html
	// https://kask.ufukty.com/2.docs.html
	// https://kask.ufukty.com/3.products.html
	// https://kask.ufukty.com/1.about/
	// https://kask.ufukty.com/2.contact/
}

func ExampleBuilder_preservedOrderingTitles() {
	b, _ := buildTestSite("testdata/preserved-ordering", "/")
	dfs([]*kask.Node{b.root3}, func(n []*kask.Node) { fmt.Println(n[len(n)-1].Title) })
	// Output:
	// Website Title
	// Career Title
	// Docs Title
	// Products Title
	// About Title
	// Contact Title
}

func ExampleBuilder_preservedOrderingBreadcrumbs() {
	b, _ := buildTestSite("testdata/preserved-ordering", "/")
	dfs([]*kask.Node{b.root3}, func(n []*kask.Node) {
		bs := each(n, func(n *kask.Node) string { return n.Title })
		fmt.Println(strings.Join(bs, " / "))
	})
	// Output:
	// Website Title
	// Website Title / Career Title
	// Website Title / Docs Title
	// Website Title / Products Title
	// Website Title / About Title
	// Website Title / Contact Title
}

func TestBuilder_cssSplitting(t *testing.T) {
	_, tmp := buildTestSite("testdata/css-splitting", "https://kask.ufukty.com/")
	fmt.Println(tmp)

	t.Run("links", func(t *testing.T) {
		f, err := os.ReadFile(filepath.Join(tmp, "a/index.html"))
		if err != nil {
			t.Errorf("prep, read file: %v", err)
		}
		content := string(f)
		t.Run("!styles.propagate.css", func(t *testing.T) {
			if strings.Contains(content, `"https://kask.ufukty.com/styles.css"`) {
				t.Errorf("assert, unexpected link")
			}
		})
		t.Run("styles.propagate.css", func(t *testing.T) {
			if !strings.Contains(content, `"https://kask.ufukty.com/styles.propagate.css"`) {
				t.Errorf("assert, expected link")
			}
		})
		t.Run("a\\styles.propagate.css", func(t *testing.T) {
			if !strings.Contains(content, `"https://kask.ufukty.com/a/styles.propagate.css"`) {
				t.Errorf("assert, expected link")
			}
		})
		t.Run("a\\styles.css", func(t *testing.T) {
			if !strings.Contains(content, `"https://kask.ufukty.com/a/styles.css"`) {
				t.Errorf("assert, expected link")
			}
		})
		if t.Failed() {
			fmt.Println(content)
		}
	})

	t.Run("contents", func(t *testing.T) {
		tcs := map[string]string{
			"/styles.css":             ":root {}",
			"/styles.propagate.css":   ":root.propagated {}",
			"/a/styles.css":           ".a {}",
			"/a/styles.propagate.css": ".a.propagated {}",
		}

		for ss, expected := range tcs {
			t.Run(strings.ReplaceAll(ss, "/", "\\"), func(t *testing.T) {
				f, err := os.ReadFile(filepath.Join(tmp, ss))
				if err != nil {
					t.Errorf("prep, read stylesheet: %v", err)
				}
				if !strings.Contains(string(f), "") {
					t.Errorf("assert, not found: %q", expected)
				}
			})
		}
	})
}

func ExampleBuilder_titles() {
	b, _ := buildTestSite("testdata/titles", "/")
	dfs([]*kask.Node{b.root3}, func(n []*kask.Node) { fmt.Println(n[len(n)-1].Title) })
	// Output:
	// .
	// An Anonymous Markdown Page
	// An Anonymous Web Page
	// A beatiful markdown file with title
	// A beautiful tmpl file with title tag
}

func ExampleBuilder_metaTitle() {
	b, _ := buildTestSite("testdata/meta-title", "/")
	dfs([]*kask.Node{b.root3}, func(n []*kask.Node) { fmt.Println(n[len(n)-1].Title) })
	// Output:
	// My Beautiful Site
	// Page
	// My Beautiful Section
	// Page
}

func TestBuilder_assets(t *testing.T) {
	_, tmp := buildTestSite("testdata/assets", "/")
	tcs := []string{".assets/sample.txt", "section/.assets/subsample.txt"}
	for _, tc := range tcs {
		assertfile(t, tmp, tc)
	}
}

func ExampleBuilder_assetLinkingInMarkdownBasedPage() {
	_, tmp := buildTestSite("testdata/asset-linking", "https://kask.ufukty.com/")
	fmt.Println(readFile(filepath.Join(tmp, "markdown.html")))
	// Output:
	// <!-- Do not edit. Auto-generated by Kask (devel) -->
	// <p><img src="https://kask.ufukty.com/.assets/img%402.jpg" alt="" /></p>
}

func ExampleBuilder_assetLinkingInTemplateBasedPage() {
	_, tmp := buildTestSite("testdata/asset-linking", "https://kask.ufukty.com/")
	fmt.Println(readFile(filepath.Join(tmp, "template.html")))
	// Output:
	// <!-- Do not edit. Auto-generated by Kask (devel) -->
	// <img src="https://kask.ufukty.com/.assets/img%402.jpg">
}

func ExampleBuilder_workersConfigurationFile() {
	tmp, err := os.MkdirTemp(os.TempDir(), "kask-test-*")
	if err != nil {
		panic(fmt.Errorf("prep, os.MkdirTemp: %w", err))
	}
	err = Build(Args{Src: "testdata/workers", Dst: tmp, Provider: ProviderCloudflareWorkers})
	if err != nil {
		panic(fmt.Errorf("Build: %w", err))
	}
	fmt.Println(readFile(filepath.Join(tmp, "_headers")))
	// Output:
	// /.assets/*
	//   Cache-Control: public, max-age=14400, must-revalidate
	//
	// /section/.assets/*
	//   Cache-Control: public, max-age=14400, must-revalidate
}

func ExampleBuilder_tmplLinkReplacements() {
	_, dst := buildTestSite("testdata/link-replacements", "/")
	fmt.Println(strings.Join(anchor.FindAllString(readFile(filepath.Join(dst, "a/tmpl.html")), -1), "\n"))
	// Output:
	// <a href="/a/b/#Title">subdir direct</a>
	// <a href="/a/b/#Title">subdir absolute</a>
	// <a href="/a/b/#Title">subdir redundancies</a>
	// <a href="/a/md.html#Title">sibling</a>
}

func ExampleBuilder_mdLinkReplacements() {
	_, dst := buildTestSite("testdata/link-replacements", "/")
	fmt.Println(strings.Join(anchor.FindAllString(readFile(filepath.Join(dst, "a/md.html")), -1), "\n"))
	// Output:
	// <a href="/a/b/#Title">subdir direct</a>
	// <a href="/a/b/#Title">subdir absolute</a>
	// <a href="/a/b/#Title">subdir redundancies</a>
	// <a href="/a/tmpl.html#Title">sibling</a>
}

func ExampleBuilder_correctLinks() {
	_, dst := buildTestSite("testdata/correct-links", "/")
	fmt.Println(strings.Join(anchor.FindAllString(readFile(filepath.Join(dst, "page1.html")), -1), "\n"))
	fmt.Println(strings.Join(anchor.FindAllString(readFile(filepath.Join(dst, "page2.html")), -1), "\n"))
	// Output:
	// <a href="/page2.html"></a>
	// <a href="/page2.html"></a>
	// <a href="/page2.html"></a>
	// <a href="/page1.html"></a>
	// <a href="/page1.html"></a>
	// <a href="/page1.html"></a>
}

func TestBuilder_docs(t *testing.T) {
	b := newBuilder(builderArgs{
		Src:    disk.NewReal("../../docs"), // TODO: use on-memory FS
		Dst:    disk.NewReal(t.TempDir()),  // TODO: use on-memory FS
		Domain: "https://kask.ufukty.com/",
	})
	err := b.Build()
	if err != nil {
		t.Errorf("act, unexpected error: %v", err)
	}
}

func ExampleBuilder_hiddenPagesDst() {
	_, tmp := buildTestSite("testdata/hidden-pages", "/")
	printFiles(tmp)
	// Output:
	// 404.html
	// career.html
	// index.html
	// products.html
	// sitemap.html
}

func ExampleBuilder_hiddenPagesSitemap() {
	b, _ := buildTestSite("testdata/hidden-pages", "/")
	dfs([]*kask.Node{b.root3}, func(n []*kask.Node) { fmt.Println(n[len(n)-1].Title) })
	// Output:
	// Index
	// Career
	// Products
}
