package builder

import (
	"bytes"
	"errors"
	"fmt"
	"html/template"
	"io"
	"path/filepath"

	"go.ufukty.com/kask/internal/paths"
	"go.ufukty.com/kask/internal/version"
	"go.ufukty.com/kask/pkg/kask"
)

func newTemplateSet() *template.Template {
	tmpl := template.New("page")
	tmpl.Funcs(template.FuncMap{
		"trustedCss":      func(s string) template.CSS { return template.CSS(s) },
		"trustedHtml":     func(s string) template.HTML { return template.HTML(s) },
		"trustedHtmlAttr": func(s string) template.HTMLAttr { return template.HTMLAttr(s) },
		"trustedJs":       func(s string) template.JS { return template.JS(s) },
		"trustedJsStr":    func(s string) template.JSStr { return template.JSStr(s) },
		"trustedSrcSet":   func(s string) template.Srcset { return template.Srcset(s) },
		"trustedUrl":      func(s string) template.URL { return template.URL(s) },
	})
	return tmpl
}

func (b *builder) propagateTemplates(d *dir2, toPropagate *template.Template) error {
	var err error
	if d.original.Kask != nil && d.original.Kask.Propagate != nil && len(d.original.Kask.Propagate.Tmpl) > 0 {
		toPropagate, err = toPropagate.ParseFiles(d.original.Kask.Propagate.Tmpl...)
		if err != nil {
			return fmt.Errorf("parsing to-propagate template files: %w", err)
		}
	}
	atLevel, err := toPropagate.Clone()
	if err != nil {
		return fmt.Errorf("cloning propagated: %w", err)
	}
	if d.original.Kask != nil && len(d.original.Kask.Tmpl) > 0 {
		atLevel, err = atLevel.ParseFiles(d.original.Kask.Tmpl...)
		if err != nil {
			return fmt.Errorf("parsing at-level template files: %w", err)
		}
	}
	d.templates = atLevel
	for _, subdir := range d.subdirs {
		if err := b.propagateTemplates(subdir, toPropagate); err != nil {
			return fmt.Errorf("%q: %w", filepath.Base(subdir.paths.Src), err)
		}
	}
	return nil
}

func pageTemplateName(path string) string {
	if filepath.Ext(path) == ".md" {
		return "markdown-page"
	}
	return "page"
}

func (b *builder) prepareTemplates(d *dir2, p paths.Paths) (*template.Template, error) {
	t, err := d.templates.Clone()
	if err != nil {
		return nil, fmt.Errorf("clone: %w", err)
	}
	if filepath.Ext(p.Src) == ".tmpl" {
		t, err = t.ParseFS(b.args.Src, p.Src)
		if err != nil {
			return nil, fmt.Errorf("parsing itself: %w", err)
		}
	}
	return t, nil
}

func versionHeader(w io.Writer) error {
	v, err := version.OfBuild()
	if err != nil {
		return fmt.Errorf("digging build info: %w", err)
	}
	_, err = fmt.Fprintf(w, "<!-- Do not edit. Auto-generated by Kask %s -->\n", v)
	if err != nil {
		return fmt.Errorf("format and write: %w", err)
	}
	return nil
}

// TODO: the [builder.htmlPostProcess] call is redundant on markdown based pages
func (b *builder) executeTemplates(p paths.Paths, t *template.Template, c *kask.TemplateContent) ([]byte, error) {
	w := bytes.NewBuffer([]byte{})
	if err := versionHeader(w); err != nil {
		return nil, fmt.Errorf("writing version header: %w", err)
	}
	if err := t.ExecuteTemplate(w, pageTemplateName(p.Src), c); err != nil {
		return nil, fmt.Errorf("executing: %w", err)
	}
	return w.Bytes(), nil
}

func (b *builder) execPage(d *dir2, p paths.Paths) error {
	if b.args.Verbose {
		fmt.Printf("printing %s\n", p.Dst)
	}
	c := &kask.TemplateContent{
		Stylesheets: d.stylesheets,
		Node:        b.leaves[p.Url],
		Root:        b.root3,
		Markdown:    b.markdown[p.Src], // otherwise `nil`
		Time:        b.start,
	}
	t, err := b.prepareTemplates(d, p)
	if err != nil {
		return fmt.Errorf("prepare: %w", err)
	}
	bs, err := b.executeTemplates(p, t, c)
	if err != nil {
		return fmt.Errorf("executing: %w", err)
	}
	bs, err = b.htmlPostProcess(p, bs)
	if err != nil {
		return fmt.Errorf("post-processing rendered html: %w", err)
	}
	if err = b.args.Dst.WriteFile(p.Dst, bs); err != nil {
		return fmt.Errorf("writing into disk: %w", err)
	}
	return nil
}

func (b *builder) print(d *dir2) error {
	if err := b.args.Dst.MkdirAll(d.paths.Dst); err != nil {
		return fmt.Errorf("creating directory: %w", err)
	}
	incorrectLinks := false
	for _, page := range d.original.Pages {
		p := d.paths.File(page, d.original.IsToStrip(), b.args.Provider.UrlMode())
		if err := b.execPage(d, p); errors.Is(err, ErrIncorrectLinks) {
			incorrectLinks = true
		} else if err != nil {
			return fmt.Errorf("%q: %w", page, err)
		}
	}
	for _, subdir := range d.subdirs {
		if err := b.print(subdir); errors.Is(err, ErrIncorrectLinks) {
			incorrectLinks = true
		} else if err != nil {
			return fmt.Errorf("%q: %w", filepath.Base(subdir.paths.Src), err)
		}
	}
	if incorrectLinks {
		return ErrIncorrectLinks
	}
	return nil
}
