name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: codeql-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  Go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with: { go-version-file: go.mod, cache: true }
      - run: go fmt ./...
      - run: go mod download
      - run: go mod verify
      - run: go mod tidy; git diff --exit-code go.mod go.sum
      - uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9
      - run: go test -race -v -timeout 600s ./...
      - uses: ufukty/golistics@v0.3.1

  DocsPreview:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - uses: actions/checkout@v6
        with: { fetch-tags: true }
      - run: make install
      - run: >
          ~/bin/kask build 
          -in docs 
          -out docs-build 
          -domain "https://pr-${{ github.event.pull_request.number }}-kask-stage.ufukty.workers.dev" 
          -v 
          -cfw
      - uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # 3.14.1 (latest atm)
        with:
          command: versions upload --preview-alias pr-${{ github.event.pull_request.number }}
          environment: stage
          wranglerVersion: 4.71.0
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
