name: Docs

on:
  push: { branches: [main], tags: "v*.*.*" }

jobs:
  DocsProd:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - uses: actions/checkout@v6
        with: { fetch-tags: true }
      - run: git checkout "$(git tag --list 'v*' --sort '-version:refname' | head -n 1)"
      - run: make install
      - run: ~/bin/kask build -in docs -out docs-build -domain "https://kask.ufukty.com" -v -cfw
      - uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # 3.14.1 (latest atm)
        with: { command: deploy, apiToken: "${{ secrets.CLOUDFLARE_API_TOKEN }}" }
