name: Docs Stage

on:
  push: { branches: [main] }

jobs:
  Stable:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - uses: actions/checkout@v6
        with: { fetch-tags: true }
      - run: make install
      - run: ~/bin/kask build -in docs -out docs-build -domain "https://kask.ufukty.com" -v -cfw
      - uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # 3.14.1 (latest atm)
        with:
          command: deploy
          environment: prod
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
